---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: call
  labels:
    app: call
spec:
  replicas: 1
  selector:
    matchLabels:
      app: call
  template:
    metadata:
      labels:
        app: call
    spec:
      containers:
        - name: call
          image: username/call:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi 
  labels:
    app: taxi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi 
  template:
    metadata:
      labels:
        app: taxi 
    spec:
      containers:
        - name: taxi 
          image: username/taxi :latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: point 
  labels:
    app: point 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point 
  template:
    metadata:
      labels:
        app: point 
    spec:
      containers:
        - name: point 
          image: username/point :latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer 
  labels:
    app: customer 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer 
  template:
    metadata:
      labels:
        app: customer 
    spec:
      containers:
        - name: customer 
          image: username/customer :latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  labels:
    app: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: username/comment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: call
  labels:
    app: call
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: call


---


apiVersion: v1
kind: Service
metadata:
  name: taxi 
  labels:
    app: taxi 
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: taxi 


---


apiVersion: v1
kind: Service
metadata:
  name: point 
  labels:
    app: point 
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: point 


---


apiVersion: v1
kind: Service
metadata:
  name: customer 
  labels:
    app: customer 
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer 


---


apiVersion: v1
kind: Service
metadata:
  name: comment
  labels:
    app: comment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: comment

